In [2]:
# Imports
import matplotlib.pyplot as plt
import numpy as np
from scipy.linalg import sqrtm
import numpy.random as rd

In [3]:
import pickle

q = pickle.load(open('A45977_Ficha2_Respostas.p', 'rb'))

#Pergunta1
q['Q001'][0,:] = np.array([0,1,0,0])
q['Q001'][1,:] = np.array([1,0,0,0])

#Pergunta2
q['Q002'][0,:] = np.array([1,0,0,0])
q['Q002'][1,:] = np.array([0,1,0,0])
q['Q002'][2,:] = np.array([0,0,1,0])
q['Q002'][3,:] = np.array([0,1,0,0])
q['Q002'][4,:] = np.array([0,0,0,1])

#Pergunta3
q['Q003'][0,:] = np.array([0,0,1,0])
q['Q003'][1,:] = np.array([0,0,0,1])
q['Q003'][2,:] = np.array([0,1,0,0])



pickle.dump(q, open('A45977_Ficha2_Respostas.p', 'wb'))

# Pergunta 1

In [5]:
from sklearn.metrics import confusion_matrix
from sklearn.neighbors import KNeighborsClassifier

file = 'A45977_Q001_data.p'

Dados = pickle.load(open(file, 'rb'))
print(Dados.keys())

Xtrain = Dados['Xtrain']
y1     = Dados['trueClassTrain']
Xtest  = Dados['Xtest']
y2     = Dados['trueClassTest']

idx1     = np.argsort(y1)
y1       = y1[idx1]
Xtrain   = Xtrain[:,idx1]

idx2     = np.argsort(y2)
y2       = y2[idx2]
Xtest    = Xtest[:,idx2]

def metricaExercicio1(x, y):
    diferencaXY = x-y
    matrizExercicio1 = np.asarray([[1, -2], 
                                   [1,  1]])
    return np.dot(np.dot(diferencaXY.T, matrizExercicio1), diferencaXY)



knn = KNeighborsClassifier(n_neighbors=29, weights='uniform', metric=metricaExercicio1).fit(Xtrain.T, y1)
y2e  = knn.predict(Xtest.T)

MC = confusion_matrix(y2, y2e)
print('Matriz de Confusão \n', MC)

V0E0 = MC[0,0]
V1E1 = MC[1,1]
V2E2 = MC[2,2]
# Erros
V0E1 = MC[0,1]
V0E2 = MC[0,2]
V1E0 = MC[1,0]
V1E2 = MC[1,2]
V2E0 = MC[2,0]
V2E1 = MC[2,1]

dict_keys(['trueClass', 'trueClassTrain', 'Xtrain', 'trueClassTest', 'Xtest'])
Matriz de Confusão 
 [[210   5   6]
 [  0 108   0]
 [  5   0  78]]


# a) ii

In [86]:
print('i) ' , V1E1) #F
print('ii) ', (V0E1 + V0E2 + V1E0 + V1E2 + V2E0 + V2E1)) #V

i)  108
ii)  16


# b) i

In [87]:
print('i)', V1E1) #V
print('ii)', V2E0) #F

i) 108
ii) 5


# Pergunta 2

In [88]:
X = np.array([[0, 2, 1, -2, 3, 1, 3, 1],
              [-1, -3, -4, -3, -2, 2, 1, -2]])
print(X)
print()
X0 = X[:,:4]
print(X0)
print()
X1 = X[:,4:]
print(X1)

[[ 0  2  1 -2  3  1  3  1]
 [-1 -3 -4 -3 -2  2  1 -2]]

[[ 0  2  1 -2]
 [-1 -3 -4 -3]]

[[ 3  1  3  1]
 [-2  2  1 -2]]


# a) i

In [89]:
m0 = np.mean(X0, axis=1)
m1 = np.mean(X1, axis=1)

Xtmp     = m0 - m1
Dmedia   = np.sum(np.abs(Xtmp),axis=0)
print('i) 4.25: ', np.round(Dmedia,2)) # V

Aux = np.dot(m0,m1)
Dmedia = 1 - Aux/np.dot(np.sqrt(np.sum(m0**2)),np.sqrt(np.sum(m1**2)))
print('ii) 0.93:  ',  np.round(Dmedia,2)) # F

i) 4.25:  4.25
ii) 0.93:   0.79


# b) ii

In [90]:
D0  = np.sqrt(np.sum((X-m0[:,np.newaxis])**2, axis=0))
D1  = np.sqrt(np.sum((X-m1[:,np.newaxis])**2, axis=0))
Dc  = np.vstack((D0, D1)) 
yec = np.argmin(Dc, axis=0)
y = np.asarray([0,0,0,0,1,1,1,1])
MC = confusion_matrix(y, yec)
print('Matriz de Confusão\n', MC)

# Se 0 > Negativo 
#    1 > Positivo
# Tem-se:
#
#        estimado
#          0  1
# real  0 TN FP
#       1 FN TP
TN = MC[0,0]
FP = MC[0,1]
FN = MC[1,0]
TP = MC[1,1]
print()
print('i)Verdadeiros Negativos é 3":', TN) # F
print('ii) Verdadeiros Positivos é 3:', TP)   # V

Matriz de Confusão
 [[4 0]
 [1 3]]

i)Verdadeiros Negativos é 3": 4
ii) Verdadeiros Positivos é 3: 3


# c) iii

In [91]:
from numpy.linalg import pinv
S0 = np.cov(X0)
S1 = np.cov(X1)

# Inverter covariância
S0i = pinv(S0)
S1i = pinv(S1)

Xi   = np.asarray([[4], [0]])
Xii  = np.asarray([[4], [-1]])
Xa   = np.hstack((Xi, Xii))
print(Xa)
D0a  = np.sqrt(np.sum((Xa-m0[:,np.newaxis])*np.dot(S0i,Xa-m0[:,np.newaxis]), axis = 0))
D1a  = np.sqrt(np.sum((Xa-m1[:,np.newaxis])*np.dot(S1i,Xa-m1[:,np.newaxis]), axis = 0))
Da   = np.vstack((D0a, D1a))
yea  = np.argmin(Da, axis=0)
print(yea)

print('i)  O vetor x = [4, 0]T é classificado na classe w1: ', yea[0]) # v
print('ii) O vetor x = [4, -1]T é classificado na classe w1: ', yea[1]) # v



[[ 4  4]
 [ 0 -1]]
[1 1]
i)  O vetor x = [4, 0]T é classificado na classe w1:  1
ii) O vetor x = [4, -1]T é classificado na classe w1:  1


# d) ii

In [92]:
Aux0 = np.dot(X.T,m0)
D0 = 1 - Aux0/np.dot(np.sqrt(np.sum(X**2)),np.sqrt(np.sum(m0**2)))
Aux1 = np.dot(X.T,m1)
D1 = 1 - Aux1/np.dot(np.sqrt(np.sum(X**2)),np.sqrt(np.sum(m1**2)))

Dd  = np.vstack((D0, D1)) 
yed = np.argmin(Dd, axis=0) 

MC = confusion_matrix(y, yed)
print('Matriz de Confusão\n', MC)
TN = MC[0,0]
FP = MC[0,1]
FN = MC[1,0]
TP = MC[1,1]
print()
print('i)  acertos na classe dos positivos é de 4: ', TP)  # F
print('ii) O número total de erros é 1:', FN+FP) # V

Matriz de Confusão
 [[4 0]
 [1 3]]

i)  acertos na classe dos positivos é de 4:  3
ii) O número total de erros é 1: 1


# e) iv

In [93]:
Xi   = np.asarray([[3], [0]])
Xii  = np.asarray([[4], [-4]])
Xb   = np.hstack((Xi, Xii))
print(Xb)
Xtmp = Xb-m0[:,np.newaxis]
D0   = np.sum(np.abs(Xtmp),axis=0)
Xtmp = Xb-m1[:,np.newaxis]
D1   = np.sum(np.abs(Xtmp),axis=0)
Db   = np.vstack((D0, D1))
yeb  = np.argmin(Db, axis=0)

print('i) O vetor x = [3, 0]T é classificado na classe w0:', yeb[0])  # F
print('ii) O vetor x = [4, -4]T é classificado na classe w1:', yeb[1]) # F

[[ 3  4]
 [ 0 -4]]
i) O vetor x = [3, 0]T é classificado na classe w0: 1
ii) O vetor x = [4, -4]T é classificado na classe w1: 0


# Pergunta 3

In [94]:
file = 'A45977_Q003_data.p'

Dados = pickle.load(open(file, 'rb'))
print(Dados.keys())
y  = Dados['trueClass']
ye = Dados['estClass']
MC = confusion_matrix(y, ye)
print('\nMatriz de Confusão \n', MC)

# Se 0 > Negativo 
#    1 > Positivo
# Tem-se:
#
#        estimado
#          0  1
# real  0 TN FP
#       1 FN TP
TN = MC[0,0]
FP = MC[0,1]
FN = MC[1,0]
TP = MC[1,1]

dict_keys(['trueClass', 'estClass'])

Matriz de Confusão 
 [[1197  103]
 [  57  643]]


# a) iii

In [95]:
print('i) A percentagem total de erro é de 8.0%:', str((FN+FP)/(TN+FP+FN+TP) * 100), '%') # V
print('ii) A percentagem de exemplos da classe dos negativos é de 65.0%:', str((FP+TN)/(TN+FP+FN+TP) * 100), '%') # V

i) A percentagem total de erro é de 8.0%: 8.0 %
ii) A percentagem de exemplos da classe dos negativos é de 65.0%: 65.0 %


# b) iv

In [96]:
precision = TP/(TP+FP)
recall    = FP/(TP+FN)

print('i) A precisão (precision) é 0.732:', str(np.round(precision, 3))) #F
print('ii) A taxa de falso positivos (falsos alarmes) é: 0.000:', str(np.round(recall, 3))) #F

i) A precisão (precision) é 0.732: 0.862
ii) A taxa de falso positivos (falsos alarmes) é: 0.000: 0.147


# c) ii

In [97]:
print('i) O número de Falsos Negativos é 96:', FN) # F
print('ii) O número de Verdadeiros Positivos é 643:', TP) # V

i) O número de Falsos Negativos é 96: 57
ii) O número de Verdadeiros Positivos é 643: 643


# Confirmação

In [98]:
QuestDic=pickle.load(open('A45977_Ficha2_Respostas.p','rb'))
# Pergunta 1
print('1a):', np.where(QuestDic['Q001'][0,:] == 1)[0][0] + 1)
print('1b):', np.where(QuestDic['Q001'][1,:] == 1)[0][0] + 1)
print()
# Pergunta 2
print('2a):', np.where(QuestDic['Q002'][0,:] == 1)[0][0] + 1)
print('2b):', np.where(QuestDic['Q002'][1,:] == 1)[0][0] + 1)
print('2c):', np.where(QuestDic['Q002'][2,:] == 1)[0][0] + 1)
print('2d):', np.where(QuestDic['Q002'][3,:] == 1)[0][0] + 1)
print('2e):', np.where(QuestDic['Q002'][4,:] == 1)[0][0] + 1)
print()
## Pergunta 3
print('3a):', np.where(QuestDic['Q003'][0,:] == 1)[0][0] + 1)
print('3b):', np.where(QuestDic['Q003'][1,:] == 1)[0][0] + 1)
print('3c):', np.where(QuestDic['Q003'][2,:] == 1)[0][0] + 1)


1a): 2
1b): 1

2a): 1
2b): 2
2c): 3
2d): 2
2e): 4

3a): 3
3b): 4
3c): 2
